<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblArticleRef', 'doctrine');

/**
 * BaseTblArticleRef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_id
 * @property integer $class_id
 * @property integer $group_id
 * @property integer $article_id
 * 
 * @method integer       getMemberId()   Returns the current record's "member_id" value
 * @method integer       getClassId()    Returns the current record's "class_id" value
 * @method integer       getGroupId()    Returns the current record's "group_id" value
 * @method integer       getArticleId()  Returns the current record's "article_id" value
 * @method TblArticleRef setMemberId()   Sets the current record's "member_id" value
 * @method TblArticleRef setClassId()    Sets the current record's "class_id" value
 * @method TblArticleRef setGroupId()    Sets the current record's "group_id" value
 * @method TblArticleRef setArticleId()  Sets the current record's "article_id" value
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblArticleRef extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_article_ref');
        $this->hasColumn('member_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'ID học sinh',
             'length' => 8,
             ));
        $this->hasColumn('class_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'ID lớp học',
             'length' => 8,
             ));
        $this->hasColumn('group_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'ID khối',
             'length' => 8,
             ));
        $this->hasColumn('article_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'ID bài viết',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'disabled' => true,
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}