all:
  sf_captchagd:
    width:            200 # Width of the image
    height:           45 # Height of the image
    words_file:       '' # Dictionary word file (empty for random text)
    resources_path:   'resources' # Path for resource files (fonts, words, etc.)
    min_word_length:  6 # Min word length (for non-dictionary random text generation)
    max_word_length:  8 # Max word length (for non-dictionary random text generation)
    session_var:      'captcha' # Sessionname to store the original text
    background_color: [255, 255, 255] # Background color in RGB-array
    colors:           [[27, 78, 181],[22, 163, 35],[214, 36, 7]] # Foreground colors in RGB-array
    shadow_color:     null # Shadow color in RGB-array or null
    line_width:       0 # Horizontal line through the text
    # Wave configuracion in X and Y axes
    y_period:       12
    y_amplitude:    14
    x_period:       11
    x_amplitude:    5
    max_rotation:   8 # letter rotation clockwise
    scale:          2 # Internal image size factor (for better image quality) 1: low, 2: medium, 3: high
    blur:           false # Blur effect for better image quality (but slower image processing). Better image results with scale=3
    debug:          false # Debug?
    image_format:   'jpeg' # Image format: jpeg or png

  conversion_image_extension: jpg
  article_image_path: /uploads/images/article
  user_image_path: /uploads/images/user
  media_server: http://myviettel.info