# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=125.212.225.193:3366;dbname=icontact
      username: icontactuser
      password: 1AFaSoz7ma72
      attributes:
        default_table_charset: utf8
        default_table_collate: utf8_general_ci