<?php

/**
 * SessionsAdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SessionsAdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SessionsAdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SessionsAdmin');
    }
}