<?php

/**
 * TblArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblArticle');
    }
}