<?php

/**
 * TblCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblComment');
    }
}