<?php

/**
 * TblGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblGroup');
    }
}