<?php

/**
 * TblMemberUserRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblMemberUserRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblMemberUserRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblMemberUserRef');
    }
}