<?php

/**
 * TblMemberActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblMemberActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblMemberActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblMemberActivity');
    }
}