<?php

/**
 * TblNotificationProgramRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblNotificationProgramRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblNotificationProgramRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblNotificationProgramRef');
    }
}