<?php

/**
 * TblNotificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblNotificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblNotificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblNotification');
    }
}