<?php

/**
 * TblOtpTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblOtpTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TblOtpTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TblOtp');
  }

  public function getOtp($email)
  {
    return $this->createQuery('a')
      ->where('a.account = ?', $email)
      ->andWhere('a.expired_time > ?', date('Y-m-d H:i:s'))
      ->fetchOne();
  }

  public function setUnLockUser($account)
  {
    return $this->createQuery('a')
      ->update()
      ->set('a.is_lock', '?', false)
      ->set('a.lock_time', '?', null)
      ->where('a.account = ?', $account)
      ->execute();
  }

  public function updateUserOtpLock($account, $time_now) {
    return $this->createQuery('a')
      ->update()
      ->set('a.is_lock', '?', true)
      ->set('a.lock_time', '?', $time_now)
      ->where('a.account = ?', $account)
      ->execute();
  }
}