<?php

/**
 * TblSummaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblSummaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblSummaryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblSummary');
    }
}