<?php

/**
 * TblSchoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblSchoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblSchoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblSchool');
    }
}