<?php

/**
 * TblUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblUserTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TblUserTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TblUser');
  }

  public function getUserByEmail($email)
  {
    return $this->createQuery('a')
      ->where('a.email = ?', $email)
      ->andWhere('a.status = 1')
      ->fetchOne();
  }

  public function updatePassword($vtUser, $password)
  {
    try {
      $vtUser->setPassword(sha1($vtUser->getSalt() . $password));
      $vtUser->save();
    } catch (Exception $e) {
      throw new Exception('Cannot update user password: ' . $e->getMessage());
    }
  }

  public function updateUserLock($email, $time_now) {
    return $this->createQuery('a')
      ->update()
      ->set('a.is_lock', '?', true)
      ->set('a.lock_time', '?', $time_now)
      ->where('a.email = ?', $email)
      ->execute();
  }

  public function updateStatus($userId, $status) {
    return $this->createQuery('a')
      ->update()
      ->set('a.message', '?', $status)
      ->where('a.id = ?', $userId)
      ->execute();
  }

  public function deleteStatus($userId) {
    return $this->createQuery('a')
      ->update()
      ->set('a.message', '?', array(null))
      ->where('a.id = ?', $userId)
      ->execute();
  }

  public function getUserByPhone($number)
  {
    return $this->createQuery('a')
      ->where('a.msisdn = ?', $number)
      ->andWhere('a.status = 1')
      ->fetchOne();
  }
}