<?php

/**
 * TblUserSigninLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblUserSigninLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblUserSigninLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblUserSigninLog');
    }

    public function resetUserSigninLock($email){
        return $this->createQuery('a')
          ->delete()
          ->where('a.user_name = ?', $email)
          ->execute();
    }

    public function deleteUserSigninLock($email, $time_log){
        return $this->createQuery('a')
          ->delete()
          ->where('a.user_name = ?', $email)
          ->andWhere('a.created_time < ?', date('Y-m-d H:i:s', $time_log))
          ->execute();
    }

    public function getCountUserSig ($email) {
        return $this->createQuery('a')
          ->where('a.user_name = ?', $email)
          ->count();
    }
}