<?php

/**
 * TblArticleImageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblArticleImageTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TblArticleImageTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TblArticleImage');
  }

  public function getActiveQuery($alias)
  {
    return $this->createQuery($alias)
      ->where($alias . '.status = 1')
      ->andWhere($alias . '.is_delete = 0');
  }

  public function getImageByIdAndUserId($id, $userId)
  {
    return $this->getActiveQuery('a')
      ->leftJoin('a.TblArticle b')
      ->andWhere('a.id = ?', $id)
      ->andWhere('b.user_id = ?', $userId)
      ->fetchOne();
  }

  public function getListImages($date, $offset, $limit, $schoolIds, $groupIds, $classIds, $memberIds)
  {
    $q = $this->getActiveQuery('ai')
      ->leftJoin('ai.TblArticle a')
      ->leftJoin('a.TblArticleRef ar')
      ->andWhere(sprintf('ar.school_id IN (%s) OR ar.group_id IN (%s) OR ar.class_id IN (%s) OR ar.member_id IN (%s)',
        implode(',', $schoolIds),
        implode(',', $groupIds),
        implode(',', $classIds),
        implode(',', $memberIds)
      ));

    if ($date) {
      $q->andWhere('ai.created_at >= ?', $date . ' 00:00:00')
        ->andWhere('ai.created_at <= ?', $date . ' 23:59:59');
    }

    return $q->offset($offset)
      ->limit($limit)
      ->orderBy('a.id DESC')
      ->execute();
  }
}