<?php

/**
 * TblArticleRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblArticleRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblArticleRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblArticleRef');
    }

    public function deleteOldData($articleId)
    {
        return $this->createQuery('a')
          ->delete()
          ->where('a.article_id = ?', $articleId)
          ->execute();
    }
}