<?php

/**
 * TblAbsenceTicketTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblAbsenceTicketTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TblAbsenceTicketTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TblAbsenceTicket');
  }

  public function getActiveQuery($alias)
  {
    return $this->createQuery($alias)
      ->andWhere($alias . '.is_delete = 0');
  }

  public function getTicketByMemberIdAndDate($memberId, $date)
  {
    return $this->getActiveQuery('at')
      ->andWhere('at.member_id = ?', $memberId)
      ->andWhere('at.date = ?', $date)
      ->fetchOne();
  }

  public function getAbsenceTicketList($fromDate, $toDate, $memberId, $classIds, $memberIds, $offset, $limit)
  {
    $q = $this->getActiveQuery('a')
      ->leftJoin('a.TblMember')
      ->andWhere('a.member_id = ?', $memberId);

    if ($classIds) {
      $q->leftJoin('a.TblClass c')
        ->andWhereIn('c.id', $classIds);
    }

    if ($memberIds) {
      $q->andWhereIn('a.member_id', $memberIds);
    }

    if ($fromDate) {
      $q->andWhere('a.date >= ?', $fromDate);
    }

    if ($toDate) {
      $q->andWhere('a.date <= ?', $toDate);
    }

    return $q->offset($offset)
      ->limit($limit)
      ->execute();
  }

  public function getActiveTicketById($id) {
    return $this->getActiveQuery('t')
      ->andWhere('t.id = ?', $id)
      ->fetchOne();
  }
}