<?php

/**
 * TblCommentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblCommentTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TblCommentTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TblComment');
  }

  public function getActiveQuery($alias)
  {
    return $this->createQuery($alias)
      ->where($alias . '.status = 1')
      ->andWhere($alias . '.is_delete = 0');
  }

  public function getCommentById($id)
  {
    return $this->getActiveQuery('a')
      ->andWhere('a.id = ?', $id)
      ->andWhere('a.parent_id IS NULL')
      ->fetchOne();
  }

  public function getListComments($kw, $offset, $limit, $articleId, $schoolIds)
  {
    $q = $this->getActiveQuery('a')
      ->leftJoin('a.TblUser u')
      ->leftJoin('u.TblUserSchoolRef r')
      ->andWhereIn('r.id', $schoolIds)
      ->andWhere('a.parent_id IS NULL');

    if ($kw) {
      $q->andWhere('a.content LIKE ?', '%' . $kw . '%');
    }

    if ($articleId) {
      $q->andWhere('a.article_id = ?', $articleId);
    } else {
      $q->andWhere('a.article_id IS NULL');
    }

    return $q->offset($offset)
      ->limit($limit)
      ->execute();
  }

  public function getCommentListByParentId($parentId)
  {
    return $this->getActiveQuery('a')
      ->andWhere('a.parent_id = ?', $parentId)
      ->execute();
  }

  public function getCommentByIdAndUserId($id, $userId, $userType = null)
  {
    $q = $this->getActiveQuery('a')
      ->andWhere('a.id = ?', $id);

    if (!$userType || $userType == UserTypeEnum::PARENTS) {
      $q->andWhere('a.user_id = ?', $userId);
    }

    return $q->fetchOne();
  }

  public function checkArticleForSchool($id, $schoolIds, $userType = UserTypeEnum::PRINCIPAL)
  {
    if ($userType == UserTypeEnum::TEACHER) {
      return $this->getActiveQuery('a')
        ->leftJoin('a.TblUser u')
        ->leftJoin('u.TblClass c')
        ->leftJoin('c.TblGroup g')
        ->leftJoin('g.TblSchool s')
        ->andWhere('a.id = ?', $id)
        ->andWhereIn('s.id', $schoolIds)
        ->count();
    } else {
      return $this->getActiveQuery('a')
        ->leftJoin('a.TblUser u')
        ->leftJoin('u.TblUserSchoolRef r')
        ->andWhere('a.id = ?', $id)
        ->andWhereIn('r.id', $schoolIds)
        ->count();
    }
  }

  public function checkCommentCredentials($id, $userId, $userType)
  {
    $schoolIds = TblSchoolTable::getInstance()->getActiveSchoolIdsByUserId($userId, $userType);
    if ($schoolIds) {
      return $this->checkArticleForSchool($id, $schoolIds, UserTypeEnum::PRINCIPAL) ||
      $this->checkArticleForSchool($id, $schoolIds, UserTypeEnum::TEACHER);
    }
    return false;
  }
}