<?php

/**
 * TblClassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblClassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblClassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblClass');
    }
}