<?php

/**
 * TblGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblGroup');
    }

    public function getActiveGroupBySchoolIdQuery($schoolId){
      return $this->createQuery()
        ->where('is_delete = 0')
        ->andWhere('school_id = ?', $schoolId);
    }

    public function getActiveGroupBySchoolId($schoolId){
      return $this->getActiveGroupBySchoolIdQuery($schoolId)
        ->fetchArray();
    }

    public function getActiveGroupByIdAndSchoolId($id,$schoolId){
      return $this->getActiveGroupBySchoolIdQuery($schoolId)
        ->andWhere('id = ?', $id)
        ->fetchOne();
    }
}