<?php

/**
 * TblMemberActivityTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblMemberActivityTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TblMemberActivityTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TblMemberActivity');
  }

  public function getActiveQuery($alias)
  {
    return $this->createQuery($alias)
      ->where($alias . '.status = 1')
      ->andWhere($alias . '.is_delete = 0');
  }

  public function getListActivities($classId, $date, $classIds = null)
  {
    $q = $this->getActiveQuery('a')
      ->leftJoin('a.TblMember b')
      ->andWhere('b.class_id = ?', $classId)
      ->andWhere('a.date = ?', $date);

    if ($classIds) {
      $q->andWhereIn('a.class_id', $classIds);
    }

    return $q->execute();
  }

  public function getMemberHistory($fromDate, $toDate, $memberId, $classIds, $memberIds, $offset, $limit)
  {
    $q = $this->getActiveQuery('a')
      ->leftJoin('a.TblMember')
      ->andWhere('a.member_id = ?', $memberId);

    if ($classIds) {
      $q->leftJoin('a.TblUserClassRef ucr')
        ->andWhereIn('ucr.class_id', $classIds);
    }

    if ($memberIds) {
      $q->andWhereIn('a.member_id', $memberIds);
    }

    if ($fromDate) {
      $q->andWhere('a.date >= ?', $fromDate);
    }

    if ($toDate) {
      $q->andWhere('a.date <= ?', $toDate);
    }

    return $q->offset($offset)
      ->limit($limit)
      ->execute();
  }

  public function getActivityByMemberIdAndDate($memberId, $date){
    return $this->createQuery()
      ->where('is_delete = 0')
      ->andWhere('member_id = ?', $memberId)
      ->andWhere('date = ?', $date)
      ->fetchOne();
  }
}