<?php

/**
 * TblMemberUserRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblMemberUserRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblMemberUserRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblMemberUserRef');
    }

    public function getMemberIdsByUserId($userId)
    {
      $arr = $this->createQuery('a')
          ->select('a.id, b.id mId, b.name mName')
          ->leftJoin('a.TblMember b')
          ->where('a.user_id = ?', $userId)
          ->andWhere('b.status = 1 AND b.is_delete = 0')
          ->execute()
          ->toKeyValueArray('mId', 'mName');
      return array_keys($arr);
    }
}