<?php

/**
 * TblMemberHealthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblMemberHealthTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblMemberHealthTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblMemberHealth');
    }

    public function getActivityByMemberIdAndDate($memberId, $date){
        return $this->createQuery()
          ->where('is_delete = 0')
          ->andWhere('member_id = ?', $memberId)
          ->andWhere('date = ?', $date)
          ->fetchOne();
    }
}