<?php

/**
 * TblMemberActivityTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblMemberActivityTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TblMemberActivityTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TblMemberActivity');
  }

  public function getActiveQuery($alias)
  {
    return $this->createQuery('a')
      ->where($alias . '.status = 1')
      ->andWhere($alias . '.is_delete = 0');
  }

  public function getListActivities($classId, $classIds = null)
  {
    $q = $this->getActiveQuery('a')
      ->andWhere('a.class_id = ?', $classId);

    if ($classIds) {
      $q->andWhereIn('a.class_id', $classIds);
    }

    return $q->fetchOne();
  }

  public function getMemberHistory($classId, $classIds = null, $memberIds = null)
  {
    $q = $this->getActiveQuery('a')
      ->andWhere('a.class_id = ?', $classId);

    if ($classIds) {
      $q->leftJoin('a.TblClass c')
        ->andWhereIn('c.id', $classIds);
    }

    if ($classIds) {
      $q->andWhereIn('a.member_id', $memberIds);
    }

    return $q->fetchOne();
  }
}