<?php

/**
 * TblMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblMenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblMenu');
    }

    public function getMenuByIdAndSchoolId($id, $schoolId){
      return $this->createQuery()
        ->where('school_id = ?', $schoolId)
        ->andWhere('id = ?', $id)
        ->fetchOne();
    }

    public function getListMenu($schoolId, $date = null){
      $query = $this->createQuery('m')
        ->leftJoin('m.TblMember')
        ->leftJoin('m.TblGroup')
        ->leftJoin('m.TblClass')
        ->where('m.school_id = ?', $schoolId);
      if($date){
        $query->andWhere('m.publish_date = ?', $date);
      }
      return $query->fetchArray();
    }
}