<?php

/**
 * TblNotificationHisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblNotificationHisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblNotificationHisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblNotificationHis');
    }
}