<?php

/**
 * TblReminderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblReminderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblReminderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblReminder');
    }
}