<?php

/**
 * TblSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblSetting');
    }

    public function getKey($key) {
        $res = $this->createQuery('a')
          ->where('a.name = ?', $key)
          ->fetchOne();
        return $res ? $res['value'] : null;
    }
}