<?php

/**
 * TblSchoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblSchoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblSchoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblSchool');
    }

    public function getActiveSchoolByUserId($userId){
      return self::getInstance()->createQuery('s')
        ->innerJoin('s.TblUserSchoolRef r')
        ->where('r.user_id = ?', $userId)
        ->andWhere('s.status = 1')
        ->fetchOne();
    }

    public function getActiveSchoolByIdAndUserId($id,$userId){
      return self::getInstance()->createQuery('s')
        ->innerJoin('s.TblUserSchoolRef r')
        ->where('r.user_id = ?', $userId)
        ->andWhere('s.id = ?', $id)
        ->andWhere('s.status = 1')
        ->fetchOne();
    }
}