<?php

/**
 * TblUserSchoolRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblUserSchoolRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblUserSchoolRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblUserSchoolRef');
    }
}