<?php

/**
 * TblUserSchoolRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblUserSchoolRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblUserSchoolRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblUserSchoolRef');
    }

    public function getSchoolIdsByUserId($userId)
    {
        return $this->createQuery('a')
          ->leftJoin('a.TblSchool b')
          ->where('a.user_id = ?', $userId)
          ->andWhere('b.status = 1 AND b.is_delete = 0')
          ->execute()->toKeyValueArray('b.id', 'b.name');
    }
}