<?php

/**
 * TblUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TblUser extends BaseTblUser
{
  public function checkPassword($password) {
    return sha1($this->getSalt() . $password) == $this->getPassword();
  }

  public function updatePassword($password)
  {
    try {
      $this->setPassword(sha1($this->getSalt() . $password));
      $this->save();
    } catch (Exception $e) {
      throw new Exception('Cannot update user password: ' . $e->getMessage());
    }
  }
}