<?php

/**
 * TblUser form.
 *
 * @package    xcode
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormTemplate.php 23810 2009-11-12 11:07:44Z Kris.Wallsmith $
 */
class TblUserApiForm extends BaseTblUserForm
{
  public function configure()
  {
    $this->useFields(['name','description','status','type','image_path','msisdn','password','tbl_class_list']);
    $this->disableCSRFProtection();
    $schoolId = $this->getOption('school_id');
    $type = $this->getOption('type');

    if($this->isNew()){
      $this->validatorSchema['password']->setOption('required',true);
    }
    $this->validatorSchema['name']->setMessage('required','Vui lòng nhập tên');
    $this->validatorSchema['name']->setMessage('max_length','Tên quá dài (tối đa %max_length% ký tự)');
    $this->validatorSchema['name']->setOption('required',true);

    $this->validatorSchema['msisdn']->setMessage('required','Vui lòng nhập SĐT');
    $this->validatorSchema['msisdn']->setMessage('max_length','SĐT quá dài (tối đa %max_length% ký tự)');
    $this->validatorSchema['msisdn']->setOption('required',$type == UserTypeEnum::PARENTS);

    $this->validatorSchema['status'] = new sfValidatorChoice([
      'choices' => array_keys(StatusEnum::getArr()),
      'required' => true
    ],[
      'invalid' => 'Trạng thái không hợp lệ',
      'required' => 'Trạng thái không được để trống'
    ]);

    $this->validatorSchema['tbl_class_list'] = new sfValidatorDoctrineChoice(array(
      'multiple' => true, 'model' => 'TblClass', 'required' => true,
      'query' => TblClassTable::getInstance()->getClassInGroupQuery(null,$schoolId)
    ), array(
      'invalid' => 'Lớp không hợp lệ',
      'required' => 'Lớp không được để trống'
    ));

    $this->validatorSchema['description']->setMessage('max_length','Mô tả quá dài (tối đa %max_length% ký tự)');

    $this->validatorSchema['image_path'] = new sfValidatorBase64Image(array(
      'max_size' => 1024*1024,
      'mime_types' => ['image/jpeg','image/png'],
      'required' => false
    ),[
      'max_size' => 'Ảnh không được quá 1MB',
      'mime_types' => 'Vui lòng upload ảnh định dạng png hoặc jpeg'
    ]);
  }

  public function processValues($values)
  {
    if(!empty($values['password'])){
      if($this->isNew()){
        $values['salt'] = VtHelper::generateSalt();
        $values['password'] = sha1($values['salt'] . $values['password']);
      }
    }
    return parent::processValues($values); // TODO: Change the autogenerated stub
  }
}
