<?php

/**
 * TblUser form.
 *
 * @package    xcode
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormTemplate.php 23810 2009-11-12 11:07:44Z Kris.Wallsmith $
 */
class TblUserApiForm extends BaseTblUserForm
{
  public function configure()
  {
    $this->useFields(['name','description','status','type','image_path','msisdn','password','tbl_class_list']);
    $this->disableCSRFProtection();

    if($this->isNew()){
      $this->validatorSchema['password']->setOption('required',true);
    }
    $this->validatorSchema['name']->setMessage('required','Vui lòng nhập tên');
    $this->validatorSchema['name']->setMessage('max_length','Tên quá dài (tối đa %max_length% ký tự)');
    $this->validatorSchema['name']->setOption('required',true);

    $this->validatorSchema['msisdn']->setMessage('required','Vui lòng nhập SĐT');
    $this->validatorSchema['msisdn']->setMessage('max_length','SĐT quá dài (tối đa %max_length% ký tự)');
    $this->validatorSchema['msisdn']->setOption('required',true);

    $this->validatorSchema['tbl_class_list']->setOption('required',true);
    $this->validatorSchema['tbl_class_list']->setMessage('required','Lớp không được để trống');
    $this->validatorSchema['tbl_class_list']->setMessage('invalid','Lớp không hợp lệ');

    $this->validatorSchema['description']->setMessage('max_length','Mô tả quá dài (tối đa %max_length% ký tự)');
  }

  public function processValues($values)
  {
    if(!empty($values['password'])){
      if($this->isNew()){
        $values['salt'] = VtHelper::generateSalt();
        $values['password'] = sha1($values['salt'] . $values['password']);
      }
    }
    return parent::processValues($values); // TODO: Change the autogenerated stub
  }
}
