<?php

/**
 * sfGuardUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserGroupTable extends PluginsfGuardUserGroupTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object sfGuardUserGroupTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('sfGuardUserGroup');
  }

  /**
   * ham thuc hien tim kiem chinh xac ten nhom nhap vao phan biet co dau và khong dau
   * @author: thongnq1
   * @created at: 03/05/2013
   * @param $query
   * @param $value
   */
  public static function applyNameFilter($query, $value)
  {
    $alias = $query->getRootAlias();
    $query->andWhere( 'LOWER('.$alias.'.name) like LOWER(?) COLLATE utf8_bin', '%'.$value['text'].'%');
  }
}