<?php

/**
 * sfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroup');
    }
  /**
   * @des:tim kiem group_name theo keyword
   * @author: loilv4
   * @created: 22/04/2013
   * @param: $keyword
   * @return: $q
   */

  public static function searchGuardGroupName($keyword) {
    # srtart - thongnq1 - 03/05/2013 - tim kiem ki tu co dau
    $keyword = addcslashes($keyword, sfConfig::get('app_addcslashes_charlist', "'%_-\\"));
    $q = Doctrine_Query::create()
      ->select('sc.id, sc.name as name')
      ->from('sfGuardGroup sc')
      ->where( 'LOWER(sc.name) like LOWER(?) COLLATE utf8_bin', '%'.trim($keyword).'%')
      #end thongnq1
      ->orderBy('sc.name asc');
    return $q;
  }
  /**
   * @des:one2money
   * @author: loilv4
   * @created: 22/04/2013
   * @param: $keyword
   * @return: $q
   */
  public static function getGuardGroupNameArrayId($arrayId) {
    return $q = sfGuardGroupTable::getInstance()->createQuery('sc')
      ->select('sc.id, sc.name as name')
      ->whereIn('sc.id', $arrayId);
  }

}