# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
signout:
  url: /signout
  param: { module: user, action: signout }

receive_password:
  url: /receivePassword
  param: { module: user, action: receivePassword }

change_password:
  url: /changePassword
  param: { module: user, action: changePassword }

signin:
  url: /signin
  param: { module: user, action: signin }

otp_verification:
  url: /otpVerification
  param: { module: user, action: otpVerification }

register:
  url: /register
  param: { module: user, action: register }

validateToken:
  url: /validateToken
  param: { module: user, action: validateToken }

updateContacts:
  url: /updateContacts
  param: { module: contact, action: updateContacts }

updateAdditionalPhone:
  url: /updateAdditionalPhone
  param: { module: contact, action: updateAdditionalPhone }

getAdditionalPhones:
  url: /getAdditionalPhones
  param: { module: contact, action: getAdditionalPhones }

deleteAdditionalPhone:
  url: /deleteAdditionalPhone
  param: { module: contact, action: deleteAdditionalPhone }

updateStatus:
  url: /updateStatus
  param: { module: user, action: updateStatus }

deleteStatus:
  url: /deleteStatus
  param: { module: user, action: deleteStatus }

getStatus:
  url: /getStatus
  param: { module: user, action: getStatus }

getInformation:
  url: /dieukhoan
  param: { module: about, action: index }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
