# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
login:
  url: /login
  param: { module: user, action: login }

receive_password:
  url: /receivePassword
  param: { module: user, action: receivePassword }

change_password:
  url: /changePassword
  param: { module: user, action: changePassword }

otp_verification:
  url: /otpVerification
  param: { module: user, action: otpVerification }

register:
  url: /register
  param: { module: user, action: register }

validateToken:
  url: /validateToken
  param: { module: user, action: validateToken }

getInformation:
  url: /dieukhoan
  param: { module: about, action: index }
############ Quan ly thong tin #############
getSchoolInfo:
  url: /getSchoolInfo
  param: { module: management, action: getSchoolInfo }
updateSchoolInfo:
  url: /updateSchoolInfo
  param: { module: management, action: updateSchoolInfo }
getGroupList:
  url: /getGroupList
  param: { module: management, action: getGroupList }
updateGroup:
  url: /updateGroup
  param: { module: management, action: updateGroup }
removeGroup:
  url: /removeGroup
  param: { module: management, action: removeGroup }
getClassList:
  url: /getClassList
  param: { module: management, action: getClassList }
updateClass:
  url: /updateClass
  param: { module: management, action: updateClass }
removeClass:
  url: /removeClass
  param: { module: management, action: removeClass }
getTeacherList:
  url: /getTeacherList
  param: { module: management, action: getTeacherList }
updateTeacher:
  url: /updateTeacher
  param: { module: management, action: updateTeacher }
removeTeacher:
  url: /removeTeacher
  param: { module: management, action: removeTeacher }
getMemberList:
  url: /getMemberList
  param: { module: management, action: getMemberList }
updateMember:
  url: /updateMember
  param: { module: management, action: updateMember }
removeMember:
  url: /removeMember
  param: { module: management, action: removeMember }
getMenuListByDate:
  url: /getMenuListByDate
  param: { module: management, action: getMenuListByDate }
updateMenuByDate:
  url: /updateMenuByDate
  param: { module: management, action: updateMenuByDate }
removeMenu:
  url: /removeMenu
  param: { module: management, action: removeMenu }
updateMemberActivity:
  url: /updateMemberActivity
  param: { module: member, action: updateMemberActivity }
############ Quan ly thong tin #############

############ Thong bao ############
updateNotificationProgram:
  url: /updateNotificationProgram
  param: { module: notification, action: updateNotificationProgram }
getNotificationProgramList:
  url: /getNotificationProgramList
  param: { module: notification, action: getNotificationProgramList }
############ END Thong bao ############

############ Bang tin ############
updateArticle:
  url: /updateArticle
  param: { module: article, action: updateArticle }
getArticleList:
  url: /getArticleList
  param: { module: article, action: getArticleList }
removeArticle:
  url: /removeArticle
  param: { module: article, action: removeArticle }
############ END Bang tin ############

############ Binh luan ############
replyComment:
  url: /replyComment
  param: { module: comment, action: replyComment }
getCommentList:
  url: /getCommentList
  param: { module: comment, action: getCommentList }
removeComment:
  url: /removeComment
  param: { module: comment, action: removeComment }
createComment:
  url: /createComment
  param: { module: comment, action: createComment }
############ END Binh luan ############

############ Theo doi hoc sinh ############
getAttendanceByClass:
  url: /getAttendanceByClass
  param: { module: member, action: getAttendanceByClass }
getMemberActivity:
  url: /getMemberActivity
  param: { module: member, action: getMemberActivity }
############ END Theo doi hoc sinh ############

############ Tong ket ############
updateSummary:
  url: /updateSummary
  param: { module: summary, action: updateSummary }
getSummaryHistory:
  url: /getSummaryHistory
  param: { module: summary, action: getSummaryHistory }
############ END Tong ket ############

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
