<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblMemberUserRef', 'doctrine');

/**
 * BaseTblMemberUserRef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_id
 * @property integer $user_id
 * @property TblMember $TblMember
 * @property TblUser $TblUser
 * 
 * @method integer          getMemberId()  Returns the current record's "member_id" value
 * @method integer          getUserId()    Returns the current record's "user_id" value
 * @method TblMember        getTblMember() Returns the current record's "TblMember" value
 * @method TblUser          getTblUser()   Returns the current record's "TblUser" value
 * @method TblMemberUserRef setMemberId()  Sets the current record's "member_id" value
 * @method TblMemberUserRef setUserId()    Sets the current record's "user_id" value
 * @method TblMemberUserRef setTblMember() Sets the current record's "TblMember" value
 * @method TblMemberUserRef setTblUser()   Sets the current record's "TblUser" value
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblMemberUserRef extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_member_user_ref');
        $this->hasColumn('member_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'ID học sinh',
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'ID phụ huynh',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TblMember', array(
             'local' => 'member_id',
             'foreign' => 'id'));

        $this->hasOne('TblUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'disabled' => true,
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}