<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblMenu', 'doctrine');

/**
 * BaseTblMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $image_path
 * @property tinyint $type
 * @property boolean $status
 * @property Doctrine_Collection $TblGroup
 * @property Doctrine_Collection $TblClass
 * @property Doctrine_Collection $TblMember
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getImagePath()   Returns the current record's "image_path" value
 * @method tinyint             getType()        Returns the current record's "type" value
 * @method boolean             getStatus()      Returns the current record's "status" value
 * @method Doctrine_Collection getTblGroup()    Returns the current record's "TblGroup" collection
 * @method Doctrine_Collection getTblClass()    Returns the current record's "TblClass" collection
 * @method Doctrine_Collection getTblMember()   Returns the current record's "TblMember" collection
 * @method TblMenu             setTitle()       Sets the current record's "title" value
 * @method TblMenu             setDescription() Sets the current record's "description" value
 * @method TblMenu             setImagePath()   Sets the current record's "image_path" value
 * @method TblMenu             setType()        Sets the current record's "type" value
 * @method TblMenu             setStatus()      Sets the current record's "status" value
 * @method TblMenu             setTblGroup()    Sets the current record's "TblGroup" collection
 * @method TblMenu             setTblClass()    Sets the current record's "TblClass" collection
 * @method TblMenu             setTblMember()   Sets the current record's "TblMember" collection
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_menu');
        $this->hasColumn('title', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tiêu đề',
             'length' => 127,
             ));
        $this->hasColumn('description', 'string', 1023, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Giới thiệu chung',
             'length' => 1023,
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ảnh minh họa',
             'length' => 255,
             ));
        $this->hasColumn('type', 'tinyint', 2, array(
             'type' => 'tinyint',
             'comment' => 'Loại thực đơn (0: Sáng - 1: Trưa - 2: Chiều)',
             'length' => 2,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái kích hoạt (0: không kích hoạt; 1: kích hoạt)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TblGroup', array(
             'refClass' => 'TblMenuRef',
             'local' => 'menu_id',
             'foreign' => 'group_id'));

        $this->hasMany('TblClass', array(
             'refClass' => 'TblMenuRef',
             'local' => 'menu_id',
             'foreign' => 'class_id'));

        $this->hasMany('TblMember', array(
             'refClass' => 'TblMenuRef',
             'local' => 'menu_id',
             'foreign' => 'member_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}