<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblNotificationProgram', 'doctrine');

/**
 * BaseTblNotificationProgram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property tinyint $type
 * @property string $title
 * @property string $content
 * @property string $image_path
 * @property integer $article_id
 * @property datetime $start_time
 * @property datetime $end_time
 * @property integer $user_id
 * @property tinyint $status
 * @property boolean $bypass
 * @property TblUser $TblUser
 * @property TblArticle $TblArticle
 * @property Doctrine_Collection $TblSchool
 * @property Doctrine_Collection $TblGroup
 * @property Doctrine_Collection $TblClass
 * @property Doctrine_Collection $TblMember
 * 
 * @method string                 getName()       Returns the current record's "name" value
 * @method tinyint                getType()       Returns the current record's "type" value
 * @method string                 getTitle()      Returns the current record's "title" value
 * @method string                 getContent()    Returns the current record's "content" value
 * @method string                 getImagePath()  Returns the current record's "image_path" value
 * @method integer                getArticleId()  Returns the current record's "article_id" value
 * @method datetime               getStartTime()  Returns the current record's "start_time" value
 * @method datetime               getEndTime()    Returns the current record's "end_time" value
 * @method integer                getUserId()     Returns the current record's "user_id" value
 * @method tinyint                getStatus()     Returns the current record's "status" value
 * @method boolean                getBypass()     Returns the current record's "bypass" value
 * @method TblUser                getTblUser()    Returns the current record's "TblUser" value
 * @method TblArticle             getTblArticle() Returns the current record's "TblArticle" value
 * @method Doctrine_Collection    getTblSchool()  Returns the current record's "TblSchool" collection
 * @method Doctrine_Collection    getTblGroup()   Returns the current record's "TblGroup" collection
 * @method Doctrine_Collection    getTblClass()   Returns the current record's "TblClass" collection
 * @method Doctrine_Collection    getTblMember()  Returns the current record's "TblMember" collection
 * @method TblNotificationProgram setName()       Sets the current record's "name" value
 * @method TblNotificationProgram setType()       Sets the current record's "type" value
 * @method TblNotificationProgram setTitle()      Sets the current record's "title" value
 * @method TblNotificationProgram setContent()    Sets the current record's "content" value
 * @method TblNotificationProgram setImagePath()  Sets the current record's "image_path" value
 * @method TblNotificationProgram setArticleId()  Sets the current record's "article_id" value
 * @method TblNotificationProgram setStartTime()  Sets the current record's "start_time" value
 * @method TblNotificationProgram setEndTime()    Sets the current record's "end_time" value
 * @method TblNotificationProgram setUserId()     Sets the current record's "user_id" value
 * @method TblNotificationProgram setStatus()     Sets the current record's "status" value
 * @method TblNotificationProgram setBypass()     Sets the current record's "bypass" value
 * @method TblNotificationProgram setTblUser()    Sets the current record's "TblUser" value
 * @method TblNotificationProgram setTblArticle() Sets the current record's "TblArticle" value
 * @method TblNotificationProgram setTblSchool()  Sets the current record's "TblSchool" collection
 * @method TblNotificationProgram setTblGroup()   Sets the current record's "TblGroup" collection
 * @method TblNotificationProgram setTblClass()   Sets the current record's "TblClass" collection
 * @method TblNotificationProgram setTblMember()  Sets the current record's "TblMember" collection
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblNotificationProgram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_notification_program');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên chương trình ',
             'length' => 255,
             ));
        $this->hasColumn('type', 'tinyint', 2, array(
             'type' => 'tinyint',
             'notnull' => true,
             'default' => 0,
             'comment' => 'Phạm vi thông báo (0 - Toàn trường; 1 - Theo khối; 2 - Theo lớp; 3 - Từng cá nhân)',
             'length' => 2,
             ));
        $this->hasColumn('title', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tiêu đề thông báo',
             'length' => 1024,
             ));
        $this->hasColumn('content', 'string', 65535, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Nội dung thông báo',
             'length' => 65535,
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Đường dẫn ảnh minh họa',
             'length' => 255,
             ));
        $this->hasColumn('article_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'Gắn thông báo vào bài viết',
             'length' => 8,
             ));
        $this->hasColumn('start_time', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             'comment' => 'Thời gian bắt đầu',
             ));
        $this->hasColumn('end_time', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             'comment' => 'Thời gian kết thúc',
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'ID người tạo',
             'length' => 8,
             ));
        $this->hasColumn('status', 'tinyint', 2, array(
             'type' => 'tinyint',
             'notnull' => true,
             'default' => 0,
             'comment' => 'Trạng thái (0: mới tạo; 1: sẵn sàng; 2: chờ gửi test; 3: đang gửi test; 4: hoàn thành test; 5: chờ gửi; 6: đang gửi; 7: hoàn thành gửi; 8: hủy)',
             'length' => 2,
             ));
        $this->hasColumn('bypass', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'comment' => 'Chấp nhận gửi ngoài giờ hành chính (0: không; 1: có)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TblUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('TblArticle', array(
             'local' => 'article_id',
             'foreign' => 'id'));

        $this->hasMany('TblSchool', array(
             'refClass' => 'TblNotificationProgramRef',
             'local' => 'program_id',
             'foreign' => 'school_id'));

        $this->hasMany('TblGroup', array(
             'refClass' => 'TblNotificationProgramRef',
             'local' => 'program_id',
             'foreign' => 'group_id'));

        $this->hasMany('TblClass', array(
             'refClass' => 'TblNotificationProgramRef',
             'local' => 'program_id',
             'foreign' => 'class_id'));

        $this->hasMany('TblMember', array(
             'refClass' => 'TblNotificationProgramRef',
             'local' => 'program_id',
             'foreign' => 'member_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}