<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblOtp', 'doctrine');

/**
 * BaseTblOtp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $account
 * @property string $otp
 * @property boolean $is_lock
 * @property integer $lock_time
 * @property timestamp $expired_time
 * 
 * @method string    getAccount()      Returns the current record's "account" value
 * @method string    getOtp()          Returns the current record's "otp" value
 * @method boolean   getIsLock()       Returns the current record's "is_lock" value
 * @method integer   getLockTime()     Returns the current record's "lock_time" value
 * @method timestamp getExpiredTime()  Returns the current record's "expired_time" value
 * @method TblOtp    setAccount()      Sets the current record's "account" value
 * @method TblOtp    setOtp()          Sets the current record's "otp" value
 * @method TblOtp    setIsLock()       Sets the current record's "is_lock" value
 * @method TblOtp    setLockTime()     Sets the current record's "lock_time" value
 * @method TblOtp    setExpiredTime()  Sets the current record's "expired_time" value
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblOtp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_otp');
        $this->hasColumn('account', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Địa chỉ mail hoặc SĐT cần xác thực',
             'length' => 255,
             ));
        $this->hasColumn('otp', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Mã otp',
             'length' => 100,
             ));
        $this->hasColumn('is_lock', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'comment' => 'Đã khóa account hay chưa',
             ));
        $this->hasColumn('lock_time', 'integer', 20, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'Thời gian khóa',
             'length' => 20,
             ));
        $this->hasColumn('expired_time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => 'Thời gian mã xác nhận còn hiệu lực',
             ));

        $this->option('comment', 'Bang luu thong tin ma xac nhan');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}