<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblGroup', 'doctrine');

/**
 * BaseTblGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $school_id
 * @property boolean $status
 * @property boolean $is_delete
 * @property TblSchool $TblSchool
 * @property Doctrine_Collection $TblClass
 * @property Doctrine_Collection $TblMenu
 * @property Doctrine_Collection $TblNotificationProgram
 * @property Doctrine_Collection $TblArticle
 * 
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getDescription()            Returns the current record's "description" value
 * @method integer             getSchoolId()               Returns the current record's "school_id" value
 * @method boolean             getStatus()                 Returns the current record's "status" value
 * @method boolean             getIsDelete()               Returns the current record's "is_delete" value
 * @method TblSchool           getTblSchool()              Returns the current record's "TblSchool" value
 * @method Doctrine_Collection getTblClass()               Returns the current record's "TblClass" collection
 * @method Doctrine_Collection getTblMenu()                Returns the current record's "TblMenu" collection
 * @method Doctrine_Collection getTblNotificationProgram() Returns the current record's "TblNotificationProgram" collection
 * @method Doctrine_Collection getTblArticle()             Returns the current record's "TblArticle" collection
 * @method TblGroup            setName()                   Sets the current record's "name" value
 * @method TblGroup            setDescription()            Sets the current record's "description" value
 * @method TblGroup            setSchoolId()               Sets the current record's "school_id" value
 * @method TblGroup            setStatus()                 Sets the current record's "status" value
 * @method TblGroup            setIsDelete()               Sets the current record's "is_delete" value
 * @method TblGroup            setTblSchool()              Sets the current record's "TblSchool" value
 * @method TblGroup            setTblClass()               Sets the current record's "TblClass" collection
 * @method TblGroup            setTblMenu()                Sets the current record's "TblMenu" collection
 * @method TblGroup            setTblNotificationProgram() Sets the current record's "TblNotificationProgram" collection
 * @method TblGroup            setTblArticle()             Sets the current record's "TblArticle" collection
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_group');
        $this->hasColumn('name', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên trường',
             'length' => 127,
             ));
        $this->hasColumn('description', 'string', 1023, array(
             'type' => 'string',
             'comment' => 'Mô tả chung',
             'length' => 1023,
             ));
        $this->hasColumn('school_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'ID trường',
             'length' => 8,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái kích hoạt (0: không kích hoạt; 1: kích hoạt)',
             ));
        $this->hasColumn('is_delete', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'comment' => 'Trạng thái xóa (0: chưa xóa - 1: đã xóa)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TblSchool', array(
             'local' => 'school_id',
             'foreign' => 'id'));

        $this->hasMany('TblClass', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('TblMenu', array(
             'refClass' => 'TblMenuRef',
             'local' => 'group_id',
             'foreign' => 'menu_id'));

        $this->hasMany('TblNotificationProgram', array(
             'refClass' => 'TblNotificationProgramRef',
             'local' => 'group_id',
             'foreign' => 'program_id'));

        $this->hasMany('TblArticle', array(
             'refClass' => 'TblArticleRef',
             'local' => 'group_id',
             'foreign' => 'article_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}