<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblMemberHealth', 'doctrine');

/**
 * BaseTblMemberHealth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_id
 * @property date $date
 * @property string $description
 * @property tinyint $health
 * @property integer $height
 * @property integer $weight
 * @property boolean $status
 * @property boolean $is_delete
 * @property TblMember $TblMember
 * 
 * @method integer         getMemberId()    Returns the current record's "member_id" value
 * @method date            getDate()        Returns the current record's "date" value
 * @method string          getDescription() Returns the current record's "description" value
 * @method tinyint         getHealth()      Returns the current record's "health" value
 * @method integer         getHeight()      Returns the current record's "height" value
 * @method integer         getWeight()      Returns the current record's "weight" value
 * @method boolean         getStatus()      Returns the current record's "status" value
 * @method boolean         getIsDelete()    Returns the current record's "is_delete" value
 * @method TblMember       getTblMember()   Returns the current record's "TblMember" value
 * @method TblMemberHealth setMemberId()    Sets the current record's "member_id" value
 * @method TblMemberHealth setDate()        Sets the current record's "date" value
 * @method TblMemberHealth setDescription() Sets the current record's "description" value
 * @method TblMemberHealth setHealth()      Sets the current record's "health" value
 * @method TblMemberHealth setHeight()      Sets the current record's "height" value
 * @method TblMemberHealth setWeight()      Sets the current record's "weight" value
 * @method TblMemberHealth setStatus()      Sets the current record's "status" value
 * @method TblMemberHealth setIsDelete()    Sets the current record's "is_delete" value
 * @method TblMemberHealth setTblMember()   Sets the current record's "TblMember" value
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblMemberHealth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_member_health');
        $this->hasColumn('member_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'ID học sinh',
             'length' => 8,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             'comment' => 'Ngày hoạt động',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Thông tin sức khỏe',
             'length' => 255,
             ));
        $this->hasColumn('health', 'tinyint', 2, array(
             'type' => 'tinyint',
             'default' => 0,
             'comment' => 'Sức khỏe (0: Ốm; 1: Bình thường; 2: Khỏe mạnh)',
             'length' => 2,
             ));
        $this->hasColumn('height', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Chiều cao (cm)',
             'length' => 5,
             ));
        $this->hasColumn('weight', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Cân nặng (kg)',
             'length' => 5,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái kích hoạt (0: không kích hoạt; 1: kích hoạt)',
             ));
        $this->hasColumn('is_delete', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'comment' => 'Trạng thái xóa (0: chưa xóa - 1: đã xóa)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TblMember', array(
             'local' => 'member_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}