<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblSetting', 'doctrine');

/**
 * BaseTblSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property enum $type
 * @property enum $cfg_type
 * @property string $value
 * @property string $params
 * @property string $group_name
 * @property string $default_value
 * @property string $credentials
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method string     getName()          Returns the current record's "name" value
 * @method string     getDescription()   Returns the current record's "description" value
 * @method enum       getType()          Returns the current record's "type" value
 * @method enum       getCfgType()       Returns the current record's "cfg_type" value
 * @method string     getValue()         Returns the current record's "value" value
 * @method string     getParams()        Returns the current record's "params" value
 * @method string     getGroupName()     Returns the current record's "group_name" value
 * @method string     getDefaultValue()  Returns the current record's "default_value" value
 * @method string     getCredentials()   Returns the current record's "credentials" value
 * @method TblSetting setId()            Sets the current record's "id" value
 * @method TblSetting setName()          Sets the current record's "name" value
 * @method TblSetting setDescription()   Sets the current record's "description" value
 * @method TblSetting setType()          Sets the current record's "type" value
 * @method TblSetting setCfgType()       Sets the current record's "cfg_type" value
 * @method TblSetting setValue()         Sets the current record's "value" value
 * @method TblSetting setParams()        Sets the current record's "params" value
 * @method TblSetting setGroupName()     Sets the current record's "group_name" value
 * @method TblSetting setDefaultValue()  Sets the current record's "default_value" value
 * @method TblSetting setCredentials()   Sets the current record's "credentials" value
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_setting');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'ID tu tang',
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 127,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'text',
              1 => 'boolean',
              2 => 'select',
              3 => 'textarea',
              4 => 'number',
              5 => 'datetime',
             ),
             'default' => 'text',
             ));
        $this->hasColumn('cfg_type', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'ALL',
              1 => 'CMS',
              2 => 'WEB',
              3 => 'WAP',
              4 => 'SMS',
             ),
             'default' => 'ALL',
             ));
        $this->hasColumn('value', 'string', 1023, array(
             'type' => 'string',
             'length' => 1023,
             ));
        $this->hasColumn('params', 'string', 1023, array(
             'type' => 'string',
             'length' => 1023,
             ));
        $this->hasColumn('group_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('default_value', 'string', 1023, array(
             'type' => 'string',
             'default' => '',
             'length' => 1023,
             ));
        $this->hasColumn('credentials', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('comment', 'Bang Luu cau hinh cua he thong');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}