<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblSummary', 'doctrine');

/**
 * BaseTblSummary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_id
 * @property date $date
 * @property integer $week
 * @property tinyint $summary
 * @property tinyint $learning
 * @property tinyint $behavior
 * @property tinyint $attendance
 * @property string $description
 * @property TblMember $TblMember
 * 
 * @method integer    getMemberId()    Returns the current record's "member_id" value
 * @method date       getDate()        Returns the current record's "date" value
 * @method integer    getWeek()        Returns the current record's "week" value
 * @method tinyint    getSummary()     Returns the current record's "summary" value
 * @method tinyint    getLearning()    Returns the current record's "learning" value
 * @method tinyint    getBehavior()    Returns the current record's "behavior" value
 * @method tinyint    getAttendance()  Returns the current record's "attendance" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method TblMember  getTblMember()   Returns the current record's "TblMember" value
 * @method TblSummary setMemberId()    Sets the current record's "member_id" value
 * @method TblSummary setDate()        Sets the current record's "date" value
 * @method TblSummary setWeek()        Sets the current record's "week" value
 * @method TblSummary setSummary()     Sets the current record's "summary" value
 * @method TblSummary setLearning()    Sets the current record's "learning" value
 * @method TblSummary setBehavior()    Sets the current record's "behavior" value
 * @method TblSummary setAttendance()  Sets the current record's "attendance" value
 * @method TblSummary setDescription() Sets the current record's "description" value
 * @method TblSummary setTblMember()   Sets the current record's "TblMember" value
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblSummary extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_summary');
        $this->hasColumn('member_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'ID học sinh',
             'length' => 8,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'comment' => 'Ngày hoạt động',
             ));
        $this->hasColumn('week', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Tuần',
             'length' => 5,
             ));
        $this->hasColumn('summary', 'tinyint', 2, array(
             'type' => 'tinyint',
             'comment' => 'Tổng kết (0: Kém; 1: Yếu; 2: TB; 3: Khá; 4: Tốt; 5: Xuất sắc)',
             'length' => 2,
             ));
        $this->hasColumn('learning', 'tinyint', 2, array(
             'type' => 'tinyint',
             'comment' => 'Tổng kết (0: Kém; 1: Yếu; 2: TB; 3: Khá; 4: Tốt; 5: Xuất sắc)',
             'length' => 2,
             ));
        $this->hasColumn('behavior', 'tinyint', 2, array(
             'type' => 'tinyint',
             'comment' => 'Tổng kết (0: Kém; 1: Yếu; 2: TB; 3: Khá; 4: Tốt; 5: Xuất sắc)',
             'length' => 2,
             ));
        $this->hasColumn('attendance', 'tinyint', 2, array(
             'type' => 'tinyint',
             'comment' => 'Đi học đầy đủ (0: Ít đi học; 1: Đầy đủ; 2: Chăm chỉ)',
             'length' => 2,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Nhận xét chung',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TblMember', array(
             'local' => 'member_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}