<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblNotificationProgram', 'doctrine');

/**
 * BaseTblNotificationProgram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property tinyint $type
 * @property string $content
 * @property integer $article_id
 * @property datetime $start_time
 * @property integer $user_id
 * @property tinyint $status
 * @property TblUser $TblUser
 * @property TblArticle $TblArticle
 * @property Doctrine_Collection $TblGroup
 * @property Doctrine_Collection $TblClass
 * @property Doctrine_Collection $TblMember
 * 
 * @method tinyint                getType()       Returns the current record's "type" value
 * @method string                 getContent()    Returns the current record's "content" value
 * @method integer                getArticleId()  Returns the current record's "article_id" value
 * @method datetime               getStartTime()  Returns the current record's "start_time" value
 * @method integer                getUserId()     Returns the current record's "user_id" value
 * @method tinyint                getStatus()     Returns the current record's "status" value
 * @method TblUser                getTblUser()    Returns the current record's "TblUser" value
 * @method TblArticle             getTblArticle() Returns the current record's "TblArticle" value
 * @method Doctrine_Collection    getTblGroup()   Returns the current record's "TblGroup" collection
 * @method Doctrine_Collection    getTblClass()   Returns the current record's "TblClass" collection
 * @method Doctrine_Collection    getTblMember()  Returns the current record's "TblMember" collection
 * @method TblNotificationProgram setType()       Sets the current record's "type" value
 * @method TblNotificationProgram setContent()    Sets the current record's "content" value
 * @method TblNotificationProgram setArticleId()  Sets the current record's "article_id" value
 * @method TblNotificationProgram setStartTime()  Sets the current record's "start_time" value
 * @method TblNotificationProgram setUserId()     Sets the current record's "user_id" value
 * @method TblNotificationProgram setStatus()     Sets the current record's "status" value
 * @method TblNotificationProgram setTblUser()    Sets the current record's "TblUser" value
 * @method TblNotificationProgram setTblArticle() Sets the current record's "TblArticle" value
 * @method TblNotificationProgram setTblGroup()   Sets the current record's "TblGroup" collection
 * @method TblNotificationProgram setTblClass()   Sets the current record's "TblClass" collection
 * @method TblNotificationProgram setTblMember()  Sets the current record's "TblMember" collection
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblNotificationProgram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_notification_program');
        $this->hasColumn('type', 'tinyint', 2, array(
             'type' => 'tinyint',
             'notnull' => true,
             'default' => 0,
             'comment' => 'Phạm vi thông báo (0 - Toàn trường; 1 - Theo khối; 2 - Theo lớp; 3 - Từng cá nhân)',
             'length' => 2,
             ));
        $this->hasColumn('content', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Nội dung thông báo',
             'length' => 1024,
             ));
        $this->hasColumn('article_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'Gắn thông báo vào bài viết',
             'length' => 8,
             ));
        $this->hasColumn('start_time', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             'comment' => 'Thời gian bắt đầu',
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'ID người tạo',
             'length' => 8,
             ));
        $this->hasColumn('status', 'tinyint', 2, array(
             'type' => 'tinyint',
             'notnull' => true,
             'default' => 0,
             'comment' => 'Trạng thái (0: nháp; 1: chờ phê duyệt; 2: phê duyệt; 3: đã gửi)',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TblUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('TblArticle', array(
             'local' => 'article_id',
             'foreign' => 'id'));

        $this->hasMany('TblGroup', array(
             'refClass' => 'TblNotificationProgramRef',
             'local' => 'program_id',
             'foreign' => 'group_id'));

        $this->hasMany('TblClass', array(
             'refClass' => 'TblNotificationProgramRef',
             'local' => 'program_id',
             'foreign' => 'class_id'));

        $this->hasMany('TblMember', array(
             'refClass' => 'TblNotificationProgramRef',
             'local' => 'program_id',
             'foreign' => 'member_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}