<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblSchool', 'doctrine');

/**
 * BaseTblSchool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $website
 * @property string $address
 * @property string $description
 * @property boolean $status
 * @property Doctrine_Collection $TblUser
 * @property Doctrine_Collection $TblGroup
 * @property Doctrine_Collection $TblMenu
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getPhone()       Returns the current record's "phone" value
 * @method string              getEmail()       Returns the current record's "email" value
 * @method string              getWebsite()     Returns the current record's "website" value
 * @method string              getAddress()     Returns the current record's "address" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method boolean             getStatus()      Returns the current record's "status" value
 * @method Doctrine_Collection getTblUser()     Returns the current record's "TblUser" collection
 * @method Doctrine_Collection getTblGroup()    Returns the current record's "TblGroup" collection
 * @method Doctrine_Collection getTblMenu()     Returns the current record's "TblMenu" collection
 * @method TblSchool           setName()        Sets the current record's "name" value
 * @method TblSchool           setPhone()       Sets the current record's "phone" value
 * @method TblSchool           setEmail()       Sets the current record's "email" value
 * @method TblSchool           setWebsite()     Sets the current record's "website" value
 * @method TblSchool           setAddress()     Sets the current record's "address" value
 * @method TblSchool           setDescription() Sets the current record's "description" value
 * @method TblSchool           setStatus()      Sets the current record's "status" value
 * @method TblSchool           setTblUser()     Sets the current record's "TblUser" collection
 * @method TblSchool           setTblGroup()    Sets the current record's "TblGroup" collection
 * @method TblSchool           setTblMenu()     Sets the current record's "TblMenu" collection
 * 
 * @package    xcode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblSchool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_school');
        $this->hasColumn('name', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên trường',
             'length' => 127,
             ));
        $this->hasColumn('phone', 'string', 15, array(
             'type' => 'string',
             'comment' => 'SĐT liên hệ',
             'length' => 15,
             ));
        $this->hasColumn('email', 'string', 63, array(
             'type' => 'string',
             'comment' => 'Email',
             'length' => 63,
             ));
        $this->hasColumn('website', 'string', 127, array(
             'type' => 'string',
             'comment' => 'Website',
             'length' => 127,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Địa chỉ',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1023, array(
             'type' => 'string',
             'comment' => 'Mô tả chung',
             'length' => 1023,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái kích hoạt (0: không kích hoạt; 1: kích hoạt)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TblUser', array(
             'refClass' => 'TblUserSchoolRef',
             'local' => 'school_id',
             'foreign' => 'user_id'));

        $this->hasMany('TblGroup', array(
             'local' => 'id',
             'foreign' => 'school_id'));

        $this->hasMany('TblMenu', array(
             'local' => 'id',
             'foreign' => 'school_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}